# Generated by Django 4.2.7 on 2024-01-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobarcode', '0002_workdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdate',
            name='shift',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
