# Generated by Django 4.2.7 on 2024-02-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobarcode', '0004_alter_workdate_eno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdate',
            name='eno',
            field=models.CharField(choices=[('E100', 'E100'), ('E200', 'E200'), ('E300', 'E300'), ('E400', 'E400'), ('E500', 'E500'), ('E600', 'E600'), ('E700', 'E700'), ('E800', 'E800'), ('E900', 'E900')], default='E100', max_length=20),
        ),
    ]
