# Generated by Django 4.2.7 on 2024-02-02 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nobarcode', '0005_alter_workdate_eno'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name_employee', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
