# Generated by Django 4.2.7 on 2024-02-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobarcode', '0006_nameemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdate',
            name='duration_time',
            field=models.IntegerField(),
        ),
    ]
